from datetime import datetime

def generate_iptables_script(iocs: list) -> str:
    ip_iocs     = [i for i in iocs if i.get("ioc_type") == "ip"]
    domain_iocs = [i for i in iocs if i.get("ioc_type") == "domain"]
    lines = [
        "#!/bin/bash",
        f"# SPECTER auto-generated firewall rules — {datetime.utcnow().isoformat()}Z",
        "# REVIEW BEFORE APPLYING. Run: sudo bash block_specter.sh", "",
        "set -euo pipefail", "",
        "echo '[SPECTER] Applying firewall rules...'", "",
    ]
    if ip_iocs:
        lines.append("# Block malicious IPs")
        for ioc in ip_iocs:
            ip = ioc["value"]
            score = ioc.get("confidence_score", 0)
            lines.append(f"iptables -I INPUT  -s {ip} -j DROP  # score={score:.0f}")
            lines.append(f"iptables -I OUTPUT -d {ip} -j DROP")
        lines.append("")
    if domain_iocs:
        lines.append("# Block domains via /etc/hosts")
        for ioc in domain_iocs:
            domain = ioc["value"]
            lines.append(f"echo '0.0.0.0  {domain}' >> /etc/hosts")
        lines.append("")
    lines.append(f"echo 'Done. Blocked {len(ip_iocs)} IPs, {len(domain_iocs)} domains.'")
    return "\n".join(lines)

def generate_pfsense_aliases(iocs: list) -> str:
    ip_iocs = [i for i in iocs if i.get("ioc_type") == "ip"]
    addr_lines = []
    for ioc in ip_iocs:
        ip = ioc["value"]
        addr_lines.append(f"  <address>{ip}</address>")
    entries = "\n".join(addr_lines)
    return f"""<?xml version="1.0"?>
<!-- SPECTER Block List — {datetime.utcnow().isoformat()}Z -->
<aliases>
  <alias>
    <name>SPECTER_BLOCKLIST</name>
    <type>host</type>
    <descr>Auto-generated by SPECTER TIP</descr>
{entries}
  </alias>
</aliases>"""
